config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/", to: 'home#index', as: 'home'
  resources :users, only: [:index, :show] do
    resources :questions, only: [:new, :create, :edit, :update]
  end

end

app/models/house.rb
# == Schema Information
#
# Table name: houses
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class House < ActiveRecord::Base
end

app/models/question.rb
 # == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  question   :text
#  choice1    :string
#  choice2    :string
#  choice3    :string
#  choice4    :string
#  answer     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  coke                   :integer
#  water                  :integer
#  baking_soda            :integer
#  money                  :integer
#  name                   :string
#  profile_picture_url    :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  	# @questions = User.find(params[:id])
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	# def new
	# 	@user = User.find params[:user_id]
	# 	@question = @user.questions.build
	# end

	# def create
 #    @user = User.find params[:user_id]
 #    @question = @user.question.build question_params
 #    if @question.save
 #      redirect_to @question.user
 #    else
 #      render "new"
 #    end
 #  end

 #  def edit
 #    @question = Question.find params[:id]
 #  end

 #  def update
 #  	@question = Question.find params[:id]
 #  	if @question.update question_params
 #      redirect_to @question.user
 #    else
 #      render "edit"
 #    end
 #  end

	# private

 #  def quit_params
 #    params.require(:question).permit(:text)
 #  end

 def create
   # @question = Question.new(params[:question])
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users = User.all
  end
  def show
  	@user = User.find params[:id]
  	# @questions = @user.questions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="splash">
	<h1>Welcome to the <br>
	<strong> Trap House </strong></h1>

	<p>A website were you trap and make money (and shit) with your friends</p>

<h3>Current Trap Stars</h3>
	<% @users.each do |user| %>
        <br>
        user:
		<%= link_to user.email, user %>
        <%= user.questions %>
	<% end %>



</div>

app/views/home/new.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
  <% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrapHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id= "user_nav">
	  <% if user_signed_in? %>
	     Signed in as <%= current_user.email %>. Not you?
	     <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	   <% else %>
	   		<table class="sign-in">
	   			<tr>
	   				<td><%= link_to "Sign up", new_user_registration_path %></td>
	   				<td><%= link_to "Sign in", new_user_session_path %></td>
	   				<td><%= link_to "Home", home_path %></td>
	   			</tr>
	   		</table>
<!--  	     <%= link_to "Sign up", new_user_registration_path %> or
 	     <%= link_to "Sign in", new_user_session_path %> -->
	   <% end %>
	 </div>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
New question for #{@user.email}
    <%= simple_form_for [@user, @quit] do |f| %>
       <%= f.input :text %>
       <%= f.button :submit %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>User's Question</h1>